### ISSUE TITLE
Error Running camel-example-2

### ISSUE THREAD

**Issue by koiralo** [ctron/kura-examples#5]
Hi @ctron , Thanks for the tutorials in kura, 
I am trying to run camel-example-2 but getting following error while uploading as a package.
I simply created the dp file and uploaded to kura. However the simple-example-1 modules runs perfectly fine.
```

2020-10-27 15:26:08,118 [qtp1335372295-31] ERROR o.e.k.w.s.GwtDeviceServiceImpl - Failed to start bundle 138
org.osgi.framework.BundleException: Could not resolve module: de.dentrassi.kura.examples.camel-example-2 [138]
  Unresolved requirement: Import-Package: org.eclipse.kura.configuration; version="[1.2.0,2.0.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383)
	at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:402)
```

And Later I get this error.
```
2020-10-27T17:34:35,284 [qtp1605793381-66] ERROR o.e.k.w.s.GwtDeviceServiceImpl - Failed to start bundle 191
org.osgi.framework.BundleException: Could not resolve module: de.dentrassi.kura.examples.camel-example-2 [191]
  Unresolved requirement: Import-Package: org.apache.camel.component.jdbc; version="[2.17.0,3.0.0)"
    -> Export-Package: org.apache.camel.component.jdbc; bundle-symbolic-name="org.apache.camel.camel-jdbc"; bundle-version="2.17.6"; version="2.17.6"; uses:="org.apache.camel,org.slf4j,org.apache.camel.impl,org.apache.camel.util,javax.sql,org.apache.camel.spi"
       org.apache.camel.camel-jdbc [190]
         Unresolved requirement: Import-Package: org.apache.camel; version="[2.17.0,2.18.0)"

	at org.eclipse.osgi.container.Module.start(Module.java:444)
```

Any help is appreciated, Thanks

**Comment by ctron** [comment]
I didn't work with Kura for a while. Looks like a dependency issue, maybe Kura did some updates that break the dependency resolution now. You can check what versions are provided and see if that matches the requirements.

I am sorry I can't be of more help at the moment.
